version: "3"
services: 
    mongodb:
        image: mongo
        volumes: 
            - .docker/data/mongodb:/data/mongodb
        restart: always
        ports:
            - "27017:27017"
        networks:
            - mongo-db-network
    redis:
        image: redis:5-alpine
        volumes:
            - .docker/data/redis:/data
        restart: always
        ports:
            - "6379:6379"
        networks: 
            - cache-network

networks:
    cache-network:
        driver: bridge
    mongo-db-network:
        driver: bridge